export const LABELS = {
ARABIC_TEXT:'وَخَلَقْنَـٰكُمْ أَزْوَٰجًۭا',
LOCAL_NIKKAH:'LOCAL NIKAH',
NIKKAH:'Local Nikkah',
EMAIL:'Email',
PASSWORD:'Password',
CONFIRM_PASSWORD:'Confirm Password',
CONTINUE:'Continue',
LOGIN:' Login',
AND:' and', 
RESEND:' Resend',
MARITAL_PROFILE:'Marital Profile',
NOT_NOW:'Not Now',
FIRST_NAME:'First Name*',
MIDDLE_NAME:'Middle Name',
LAST_NAME:'Last Name*',
FULL_NAME:'Full Name',
DISPLAY_NAME:'Display Name',
MAN:'Man',
WOMAN:'Woman',
CHANGE_PASSWORD:'Change Password',
LOGOUT:'Logout',
PARHELION:'Parhelion',
PARHELION_Email:'the.parhelion@gmail.com'

};

export const CLAUSES ={
CREATED_IN_PAIRS:'and we created you in pairs',
FIND_SPOUSE:'Find your spouse with the help of a local masjid',
GOOGLE:'Continue with Google',
APPLE:'Continue with Apple',
EMAIL:'Continue with Email',
EMAIL_SIGNUP:'Continue with email',
BY_CONTINUING:'By Continuing, you are agreeing to our ',
TERMS_AND_SERVICES:'Terms & Services',
BOLD_PRIVACY: ' Privacy Policy',
ENTER_EMAIL:'Enter your email',
ENTER_PASSWORD:'Enter your password',
CONFIRM_YOUR_PASSWORD:'Confirm your password',
ALREADY_ACCOUNT:'Already have an account?',
VERIFY_EMAIL:'Verify your Email',
CONFIRMATION_CODE:'We have sent a confirmation code on',
RECIEVE_CODE:"Didn't receive a code?",
CHOOSE_MASJID:'Choose your local Masjid',
MASJID1:'Bentonville Islamic Center',
MASJID2:'Islamic Center of America',
MASJID3:'Islamic Center of Orlando',
MASJID4:'The Islamic Center of Southern California',
CREATE_MARITAL:'Create Marital Profile',
CREATE_PROFILE_TEXT:'Marital profile is what potential spouse see in the app. Would you like to create one?',
WHATS_NAME:"What's your name?",
SHARE_GENDER:'Please share your gender',
SHARE_DOB:'Please share your date of \nbirth',
EDIT_DETAILS:'Edit account details',
PROFILE_SUBMITTED:'Marital profile: submitted',

};