export const GELASIOBOLD='Gelasio-Bold'
export const INTER_BOLD='Inter_24pt-Bold'
export const INTER_REGULAR='Inter_18pt-Regular'
export const FUTURA_MEDIUM='FuturaMediumBT'
export const AMIRI_QURAN='AmiriQuran-Regular'
export const INTER_MEDIUM='Inter_18pt-Medium'